[functions.generate-assessment-questions]
verify_jwt = true

[functions.visitor-chat]
verify_jwt = false

[functions.admin-visitor-chat]
verify_jwt = true

[functions.request-backoffice-password-reset]
verify_jwt = false
