-- Admin Activity Logs setup
-- Run this in Supabase SQL Editor to enable custom admin audit events

create table if not exists public.admin_activity_logs (
  log_id bigint generated by default as identity primary key,
  admin_id uuid null references public.admin(admin_id) on delete set null,
  actor_name text null,
  action text not null,
  action_type text not null default 'edit',
  details text null,
  status text not null default 'SUCCESS',
  metadata jsonb null default '{}'::jsonb,
  performed_at timestamptz not null default now()
);

create index if not exists idx_admin_activity_logs_performed_at
  on public.admin_activity_logs (performed_at desc);

create index if not exists idx_admin_activity_logs_admin_id
  on public.admin_activity_logs (admin_id);

alter table public.admin_activity_logs enable row level security;

-- Admin can insert activity logs
drop policy if exists "admin_activity_logs_insert_admin" on public.admin_activity_logs;

create policy "admin_activity_logs_insert_admin"
on public.admin_activity_logs
for insert
to authenticated
with check (
  exists (
    select 1
    from public.admin a
    where a.admin_id = auth.uid()
      and lower(a.role) = 'admin'
  )
);

-- Admin can read activity logs
drop policy if exists "admin_activity_logs_select_admin" on public.admin_activity_logs;

create policy "admin_activity_logs_select_admin"
on public.admin_activity_logs
for select
to authenticated
using (
  exists (
    select 1
    from public.admin a
    where a.admin_id = auth.uid()
      and lower(a.role) = 'admin'
  )
);
