-- Personnel Activity Logs setup
-- Run this in Supabase SQL Editor to enable the personnel-facing Audit Logs page

create table if not exists public.personnel_activity_logs (
  log_id bigint generated by default as identity primary key,
  personnel_id uuid not null references public.admin(admin_id) on delete cascade,
  activity_type text not null,
  action text not null,
  details text null,
  status text not null default 'SUCCESS',
  metadata jsonb null default '{}'::jsonb,
  performed_at timestamptz not null default now()
);

-- Structured link to the acknowledged announcement, used for the
-- "Announcement Acknowledged" audit entry and its duplicate-prevention index.
alter table public.personnel_activity_logs
  add column if not exists announcement_id uuid null references public.announcements(announcement_id) on delete set null;

create index if not exists idx_personnel_activity_logs_performed_at
  on public.personnel_activity_logs (performed_at desc);

create index if not exists idx_personnel_activity_logs_personnel_id
  on public.personnel_activity_logs (personnel_id);

create index if not exists idx_personnel_activity_logs_announcement_id
  on public.personnel_activity_logs (announcement_id);

-- One "Announcement Acknowledged" audit row per personnel + announcement.
drop index if exists personnel_activity_logs_announcement_ack_uidx;
create unique index personnel_activity_logs_announcement_ack_uidx
  on public.personnel_activity_logs (personnel_id, announcement_id)
  where activity_type = 'announcement_acknowledged';

alter table public.personnel_activity_logs enable row level security;

-- Personnel can insert their own activity logs
drop policy if exists "personnel_activity_logs_insert_self" on public.personnel_activity_logs;

create policy "personnel_activity_logs_insert_self"
on public.personnel_activity_logs
for insert
to authenticated
with check (
  personnel_id = auth.uid()
);

-- Personnel can read only their own activity logs
drop policy if exists "personnel_activity_logs_select_self" on public.personnel_activity_logs;

create policy "personnel_activity_logs_select_self"
on public.personnel_activity_logs
for select
to authenticated
using (
  personnel_id = auth.uid()
);

-- Idempotent backfill: create the missing "Announcement Acknowledged" audit
-- entry for every existing announcement_acknowledgments row that doesn't have
-- one yet. Safe to re-run — the unique index above makes repeat runs a no-op.
insert into public.personnel_activity_logs (
  personnel_id, activity_type, action, details, status, metadata, announcement_id, performed_at
)
select
  ack.personnel_id,
  'announcement_acknowledged',
  'Announcement Acknowledged',
  'Reviewed and acknowledged the assigned announcement.',
  'SUCCESS',
  jsonb_build_object('announcement_id', ack.announcement_id, 'announcement_title', an.title),
  ack.announcement_id,
  ack.acknowledged_at
from public.announcement_acknowledgments ack
join public.announcements an on an.announcement_id = ack.announcement_id
on conflict (personnel_id, announcement_id) where activity_type = 'announcement_acknowledged' do nothing;
