export const LANDING_LANGUAGE_STORAGE_KEY = 'ignis-safe:landing-language';

export const normalizeDasmarinasText = (value) => {
  if (typeof value !== 'string') return value;

  return value
    .replace(/DASMARINAS/g, 'DASMARIÑAS')
    .replace(/Dasmarinas/g, 'Dasmariñas')
    .replace(/dasmarinas/g, 'dasmariñas');
};

export const getLocalizedSection = (section, language) => {
  if (!section || typeof section !== 'object') return section;
  if (language !== 'tagalog') return section;
  return { ...section, ...(section.tagalog || {}) };
};

const UI_COPY = {
  english: {
    languageCode: 'EN',
    languageName: 'English',
    alternateLanguageName: 'Filipino',
    emergencyMessage: 'Emergency? Call 911 immediately.',
    stationHotlines: 'Station hotlines',
    home: 'Home',
    mobileApp: 'Mobile App',
    resources: 'Resources',
    announcements: 'Announcements',
    onlineApplication: 'Online Application',
    aboutUs: 'About Us',
    faq: 'FAQ',
    organizationalChart: 'Organizational Chart',
    publicInformation: 'Public information',
    organizationalChartNote: 'Current leadership and personnel structure of the Bureau of Fire Protection Dasmariñas City Fire Station.',
    loadingOrganizationalChart: 'Loading organizational chart...',
    contactUs: 'Contact Us',
    sendMessage: 'Send Us a Message',
    login: 'Login',
    mobileAppDownloadTitle: 'Download IGNIS SAFE',
    mobileAppDownloadIntro: 'The Android application will be available here after the final APK has been tested and approved.',
    mobileAppQrPending: 'QR code available on release',
    mobileAppInstallTitle: 'How to install',
    mobileAppInstallStepOne: 'Download the official APK from this page.',
    mobileAppInstallStepTwo: 'Open the downloaded file on your Android phone.',
    mobileAppInstallStepThree: 'Follow the Android installation prompts.',
    mobileAppEyebrow: 'Official mobile application',
    mobileAppTitle: 'Fire safety guidance, ready for your Android phone',
    mobileAppDescription: 'The IGNIS SAFE mobile application is being prepared for public release. Its official APK download, version information, and secure installation guide will be published here once finalized.',
    mobileAppShowcaseTitle: 'Learn. Practice. Stay prepared.',
    mobileAppShowcaseText: 'Access focused fire safety lessons, guided simulations, learning progress, and achievement badges in one mobile experience.',
    mobileAppPreviewLabel: 'Preview of the IGNIS SAFE mobile application',
    mobileAppPreviewNote: 'App preview. Final screens may change.',
    mobileAppHighlightsLabel: 'Mobile application information',
    mobileAppOfficial: 'Official BFP Dasmariñas release',
    mobileAppAndroidOnly: 'Android devices only',
    mobileAppVerifiedRelease: 'Signed release build',
    downloadApk: 'Download APK',
    downloadApkComingSoon: 'APK Coming Soon',
    mobileAppPlaceholderNote: 'The download will be enabled after the final application file has been verified and published.',
    mobileAppReleaseStatus: 'Release status',
    mobileAppPreparingBuild: 'Preparing the official build',
    mobileAppPlatform: 'Platform',
    mobileAppFormat: 'File format',
    mobileAppVersion: 'Version',
    mobileAppAwaitingRelease: 'Awaiting final release',
    mobileAppAvailability: 'Availability',
    mobileAppComingSoon: 'Coming soon',
    mobileAppQrTitle: 'QR download will appear here',
    mobileAppQrNote: 'The official QR code will be added together with the finalized APK.',
    heroEyebrow: 'Official city fire station portal',
    startApplication: 'Start online application',
    viewRequirements: 'View requirements',
    servicesAvailable: 'Station services and online guidance available',
    fsicFsec: 'FSIC & FSEC',
    requirementsProcess: 'Requirements and application process',
    publicAdvisories: 'Public advisories',
    latestUpdates: 'Latest announcements and updates',
    contactStation: 'Contact the station',
    hotlinesChannels: 'Hotlines and official channels',
    publicNotice: 'Public notice',
    latestAnnouncements: 'Latest announcements',
    announcementNote: 'Official updates posted for the public audience on the landing page.',
    loadingAnnouncements: 'Loading announcements...',
    noAnnouncements: 'No public announcements yet.',
    publicLabel: 'Public',
    seeMore: 'See more',
    seeLess: 'See less',
    viewFullAnnouncement: 'View full announcement',
    closeAnnouncement: 'Close announcement',
    openOriginalImage: 'Open original image',
    previousPage: 'Previous page',
    nextPage: 'Next page',
    page: 'Page',
    of: 'of',
    servingCity: 'Serving Dasmariñas',
    viewOrgChart: 'View organizational chart',
    processEyebrow: 'Step-by-step processing guide',
    processDescription: 'Follow the required account, application, payment, and document-release steps.',
    goToPortal: 'Go to ',
    orScanQr: ' or scan the QR code below.',
    openFsisPortal: 'Open the FSIS online application portal',
    quickAnswers: 'Quick answers',
    landline: 'Landline',
    mobile: 'Mobile',
    email: 'Email',
    facebook: 'Facebook',
    copy: 'Copy',
    copied: 'Copied',
    copyValue: 'Copy',
    explore: 'Explore',
    contactAndEmergency: 'Contact and Emergency',
    emergencyHotline: 'Emergency hotline',
    footerSummary: 'Serving the community through fire prevention, emergency response, and public safety education.',
    rightsReserved: 'All rights reserved.',
    terms: 'Terms',
    privacy: 'Privacy',
    messageUs: 'Message Us',
    close: 'Close',
  },
  tagalog: {
    languageCode: 'FIL',
    languageName: 'Filipino',
    alternateLanguageName: 'English',
    emergencyMessage: 'May emergency? Tumawag agad sa 911.',
    stationHotlines: 'Mga hotline ng istasyon',
    home: 'Home',
    mobileApp: 'Mobile App',
    resources: 'Mga Serbisyo',
    announcements: 'Mga Anunsyo',
    onlineApplication: 'Online na Aplikasyon',
    aboutUs: 'Tungkol sa Amin',
    faq: 'Mga Madalas Itanong',
    organizationalChart: 'Organizational Chart',
    publicInformation: 'Pampublikong impormasyon',
    organizationalChartNote: 'Kasalukuyang pamunuan at estruktura ng mga tauhan ng Bureau of Fire Protection Dasmariñas City Fire Station.',
    loadingOrganizationalChart: 'Kinukuha ang organizational chart...',
    contactUs: 'Makipag-ugnayan',
    sendMessage: 'Magpadala ng Mensahe',
    login: 'Mag-login',
    mobileAppDownloadTitle: 'I-download ang IGNIS SAFE',
    mobileAppDownloadIntro: 'Magiging available dito ang Android application pagkatapos masubukan at maaprubahan ang final APK.',
    mobileAppQrPending: 'Magiging available ang QR code sa release',
    mobileAppInstallTitle: 'Paraan ng pag-install',
    mobileAppInstallStepOne: 'I-download ang opisyal na APK mula sa pahinang ito.',
    mobileAppInstallStepTwo: 'Buksan ang na-download na file sa iyong Android phone.',
    mobileAppInstallStepThree: 'Sundin ang installation prompts ng Android.',
    mobileAppEyebrow: 'Opisyal na mobile application',
    mobileAppTitle: 'Gabay sa kaligtasan sa sunog para sa iyong Android phone',
    mobileAppDescription: 'Inihahanda ang IGNIS SAFE mobile application para sa pampublikong release. Ilalagay dito ang opisyal na APK download, impormasyon ng bersyon, at ligtas na gabay sa pag-install kapag handa na ito.',
    mobileAppShowcaseTitle: 'Matuto. Magsanay. Maging handa.',
    mobileAppShowcaseText: 'Makakuha ng fire safety lessons, guided simulations, learning progress, at achievement badges sa iisang mobile experience.',
    mobileAppPreviewLabel: 'Preview ng IGNIS SAFE mobile application',
    mobileAppPreviewNote: 'App preview. Maaaring magbago ang final screens.',
    mobileAppHighlightsLabel: 'Impormasyon tungkol sa mobile application',
    mobileAppOfficial: 'Opisyal na release ng BFP Dasmariñas',
    mobileAppAndroidOnly: 'Para lamang sa Android devices',
    mobileAppVerifiedRelease: 'Signed na release build',
    downloadApk: 'I-download ang APK',
    downloadApkComingSoon: 'Malapit na ang APK',
    mobileAppPlaceholderNote: 'Magiging available ang download pagkatapos ma-verify at mai-publish ang final application file.',
    mobileAppReleaseStatus: 'Status ng release',
    mobileAppPreparingBuild: 'Inihahanda ang opisyal na build',
    mobileAppPlatform: 'Platform',
    mobileAppFormat: 'Uri ng file',
    mobileAppVersion: 'Bersyon',
    mobileAppAwaitingRelease: 'Hinihintay ang final release',
    mobileAppAvailability: 'Availability',
    mobileAppComingSoon: 'Malapit na',
    mobileAppQrTitle: 'Dito ilalagay ang QR download',
    mobileAppQrNote: 'Idadagdag ang opisyal na QR code kasama ng finalized APK.',
    heroEyebrow: 'Opisyal na portal ng city fire station',
    startApplication: 'Simulan ang online na aplikasyon',
    viewRequirements: 'Tingnan ang mga kinakailangan',
    servicesAvailable: 'Available ang mga serbisyo at online na gabay ng istasyon',
    fsicFsec: 'FSIC at FSEC',
    requirementsProcess: 'Mga kinakailangan at proseso ng aplikasyon',
    publicAdvisories: 'Mga pampublikong abiso',
    latestUpdates: 'Pinakabagong mga anunsyo at update',
    contactStation: 'Makipag-ugnayan sa istasyon',
    hotlinesChannels: 'Mga hotline at opisyal na channel',
    publicNotice: 'Pampublikong abiso',
    latestAnnouncements: 'Pinakabagong mga anunsyo',
    announcementNote: 'Mga opisyal na update para sa publiko sa landing page.',
    loadingAnnouncements: 'Kinukuha ang mga anunsyo...',
    noAnnouncements: 'Wala pang pampublikong anunsyo.',
    publicLabel: 'Pampubliko',
    seeMore: 'Tingnan pa',
    seeLess: 'Paikliin',
    viewFullAnnouncement: 'Tingnan ang buong anunsyo',
    closeAnnouncement: 'Isara ang anunsyo',
    openOriginalImage: 'Buksan ang orihinal na larawan',
    previousPage: 'Nakaraang pahina',
    nextPage: 'Susunod na pahina',
    page: 'Pahina',
    of: 'ng',
    servingCity: 'Naglilingkod sa Dasmariñas',
    viewOrgChart: 'Tingnan ang organizational chart',
    processEyebrow: 'Gabay sa bawat hakbang',
    processDescription: 'Sundin ang mga hakbang para sa account, aplikasyon, pagbabayad, at pagkuha ng dokumento.',
    goToPortal: 'Pumunta sa ',
    orScanQr: ' o i-scan ang QR code sa ibaba.',
    openFsisPortal: 'Buksan ang FSIS online application portal',
    quickAnswers: 'Mabilis na sagot',
    landline: 'Landline',
    mobile: 'Mobile',
    email: 'Email',
    facebook: 'Facebook',
    copy: 'Kopyahin',
    copied: 'Nakopya',
    copyValue: 'Kopyahin',
    explore: 'Tingnan',
    contactAndEmergency: 'Ugnayan at Emergency',
    emergencyHotline: 'Emergency hotline',
    footerSummary: 'Naglilingkod sa komunidad sa pamamagitan ng pag-iwas sa sunog, emergency response, at edukasyong pangkaligtasan.',
    rightsReserved: 'Lahat ng karapatan ay nakalaan.',
    terms: 'Mga Tuntunin',
    privacy: 'Privacy',
    messageUs: 'Mag-message',
    close: 'Isara',
  },
};

export const getLandingUiCopy = (language) => UI_COPY[language] || UI_COPY.english;
