create table if not exists public.visitor_conversations (
  id uuid primary key default gen_random_uuid(),
  visitor_label text not null unique,
  visitor_name text not null check (char_length(visitor_name) between 2 and 80),
  visitor_email text not null check (char_length(visitor_email) between 3 and 254),
  access_code_hash text not null unique,
  status text not null default 'open' check (status in ('open', 'resolved')),
  last_message_preview text not null default '',
  last_sender_type text check (last_sender_type in ('visitor', 'admin', 'system')),
  last_message_at timestamptz not null default now(),
  visitor_last_read_at timestamptz,
  admin_last_read_at timestamptz,
  resolved_at timestamptz,
  resolved_by uuid references public.admin(admin_id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.visitor_messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.visitor_conversations(id) on delete cascade,
  client_message_id uuid,
  sender_type text not null check (sender_type in ('visitor', 'admin', 'system')),
  sender_admin_id uuid references public.admin(admin_id) on delete set null,
  body text not null check (char_length(btrim(body)) between 1 and 1500),
  created_at timestamptz not null default now(),
  constraint visitor_messages_sender_check check (
    (sender_type = 'admin' and sender_admin_id is not null)
    or (sender_type in ('visitor', 'system') and sender_admin_id is null)
  ),
  constraint visitor_messages_client_message_unique unique (conversation_id, client_message_id)
);

create table if not exists public.visitor_chat_rate_events (
  id bigint generated by default as identity primary key,
  key_hash text not null,
  action text not null check (action in ('start', 'restore', 'message')),
  occurred_at timestamptz not null default now()
);

create index if not exists visitor_conversations_last_message_idx
  on public.visitor_conversations (last_message_at desc);

create index if not exists visitor_conversations_status_last_message_idx
  on public.visitor_conversations (status, last_message_at desc);

create index if not exists visitor_messages_conversation_created_idx
  on public.visitor_messages (conversation_id, created_at, id);

create index if not exists visitor_chat_rate_events_lookup_idx
  on public.visitor_chat_rate_events (key_hash, action, occurred_at desc);

alter table public.visitor_conversations enable row level security;
alter table public.visitor_messages enable row level security;
alter table public.visitor_chat_rate_events enable row level security;

revoke all on table public.visitor_conversations from anon, authenticated;
revoke all on table public.visitor_messages from anon, authenticated;
revoke all on table public.visitor_chat_rate_events from anon, authenticated;
revoke all on sequence public.visitor_chat_rate_events_id_seq from anon, authenticated;

grant all on table public.visitor_conversations to service_role;
grant all on table public.visitor_messages to service_role;
grant all on table public.visitor_chat_rate_events to service_role;
grant usage, select on sequence public.visitor_chat_rate_events_id_seq to service_role;

comment on table public.visitor_conversations is
  'Account-free website visitor conversations. Access codes are stored only as SHA-256 hashes.';

comment on table public.visitor_messages is
  'Messages exchanged between anonymous website visitors and authenticated administrators.';

comment on table public.visitor_chat_rate_events is
  'Short-lived hashed request buckets used to enforce visitor chat abuse limits without storing raw IP addresses.';
